Nop.Plugin.Widget.NopSlider/Controllers/SliderController.cs
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Data;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Media;
using Nop.Plugin.Widget.NopSlider.Domain;
using Nop.Plugin.Widgets.NopSlider.Model;
using Nop.Plugin.Widgets.NopSlider.Service;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Services.Vendors;
using Nop.Web.Extensions;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Web.Models.Catalog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Nop.Plugin.Widgets.NopSlider.Controllers
{
    [AdminAuthorize]
    public class SliderController : BasePluginController
    {
        #region Fields
        private IRepository<Slider> _sliderRepo;
        private ISliderService _sliderService;
        private IRepository<Item> _itemRepo;
        private IPictureService _pictureService;
        private ICacheManager _cacheService;
        private readonly IProductService _productService;
        private readonly IProductTemplateService _productTemplateService;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly ICustomerService _customerService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly ITaxCategoryService _taxCategoryService;
        private readonly IProductTagService _productTagService;
        private readonly ICopyProductService _copyProductService;
        private readonly IPdfService _pdfService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        private readonly IAclService _aclService;
        private readonly IStoreService _storeService;
        private readonly IOrderService _orderService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IVendorService _vendorService;
        private readonly IShippingService _shippingService;
        private readonly IShipmentService _shipmentService;
        private readonly ICurrencyService _currencyService;
        private readonly CurrencySettings _currencySettings;
        private readonly IMeasureService _measureService;
        private readonly MeasureSettings _measureSettings;
        private readonly AdminAreaSettings _adminAreaSettings;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IDiscountService _discountService;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IProductAttributeFormatter _productAttributeFormatter;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IDownloadService _downloadService;
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly IStoreContext _storeContext;
        private readonly IPriceFormatter _priceFormatter;
        private readonly ITaxService _taxService;
        private readonly IWebHelper _webHelper;
        private readonly ICacheManager _cacheManager;
        private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
        private IItemService _itemService;

        #endregion

        #region Constructors
        public SliderController(IRepository<Slider> sliderRepo,
            ISliderService sliderService, IItemService itemService, IRepository<Item> itemRepo,
            ICacheManager cacheManager, IPictureService pictureService,
            IPermissionService permissionService,
            IProductService productService,
            IProductTemplateService productTemplateService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            ICustomerService customerService,
            IUrlRecordService urlRecordService,
            IWorkContext workContext,
            ILanguageService languageService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            ISpecificationAttributeService specificationAttributeService,
            ITaxCategoryService taxCategoryService,
            IProductTagService productTagService,
            ICopyProductService copyProductService,
            IPdfService pdfService,
            IExportManager exportManager,
            IImportManager importManager,
            ICustomerActivityService customerActivityService,
            IAclService aclService,
            IStoreService storeService,
            IOrderService orderService,
            IStoreMappingService storeMappingService,
            IVendorService vendorService,
            IShippingService shippingService,
            IShipmentService shipmentService,
            ICurrencyService currencyService,
            CurrencySettings currencySettings,
            IMeasureService measureService,
            MeasureSettings measureSettings,
            AdminAreaSettings adminAreaSettings,
            IDateTimeHelper dateTimeHelper,
            IDiscountService discountService,
            IProductAttributeService productAttributeService,
            IBackInStockSubscriptionService backInStockSubscriptionService,
            IShoppingCartService shoppingCartService,
            IProductAttributeFormatter productAttributeFormatter,
            IProductAttributeParser productAttributeParser,
            IDownloadService downloadService,
            IStoreContext storeContext,
            IPriceCalculationService priceCalculationService,
            IPriceFormatter priceFormatter,
            ITaxService taxService,
            IWebHelper webHelper,
            MediaSettings mediaSettings,
            CatalogSettings catalogSettings
            )
        {
            this._cacheService = cacheManager;
            _pictureService = pictureService;
            _sliderRepo = sliderRepo;
            _sliderService = sliderService;
            _itemService = itemService;
            _itemRepo = itemRepo;
            this._permissionService = permissionService;
            this._productService = productService;
            this._productTemplateService = productTemplateService;
            this._categoryService = categoryService;
            this._manufacturerService = manufacturerService;
            this._customerService = customerService;
            this._urlRecordService = urlRecordService;
            this._workContext = workContext;
            this._languageService = languageService;
            this._localizationService = localizationService;
            this._localizedEntityService = localizedEntityService;
            this._specificationAttributeService = specificationAttributeService;
            this._pictureService = pictureService;
            this._taxCategoryService = taxCategoryService;
            this._productTagService = productTagService;
            this._copyProductService = copyProductService;
            this._pdfService = pdfService;
            this._exportManager = exportManager;
            this._importManager = importManager;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;
            this._aclService = aclService;
            this._storeService = storeService;
            this._orderService = orderService;
            this._storeMappingService = storeMappingService;
            this._vendorService = vendorService;
            this._shippingService = shippingService;
            this._shipmentService = shipmentService;
            this._currencyService = currencyService;
            this._currencySettings = currencySettings;
            this._measureService = measureService;
            this._measureSettings = measureSettings;
            this._adminAreaSettings = adminAreaSettings;
            this._dateTimeHelper = dateTimeHelper;
            this._discountService = discountService;
            this._productAttributeService = productAttributeService;
            this._backInStockSubscriptionService = backInStockSubscriptionService;
            this._shoppingCartService = shoppingCartService;
            this._productAttributeFormatter = productAttributeFormatter;
            this._productAttributeParser = productAttributeParser;
            this._downloadService = downloadService;
            this._priceCalculationService = priceCalculationService;
            this._taxService = taxService;
            this._priceFormatter = priceFormatter;
            this._webHelper = webHelper;
            this._mediaSettings = mediaSettings;
            this._catalogSettings = catalogSettings;
            this._storeContext = storeContext;
            this._cacheManager = cacheManager;
        }

Nop.Plugin.Widget.NopSlider/Views/Configuration.cshtml
<p>Configure from control panel</p>

Nop.Plugin.Widget.NopSlider/Views/ManageItems.cshtml
@using Nop.Plugin.Widgets.NopSlider.Domain.Enum
@using Nop.Web.Framework;
@using Nop.Web.Framework.UI;
@model Nop.Plugin.Widgets.NopSlider.Model.ItemModel


<script type="text/javascript">
        $(document).ready(function() {


            $('#addProductPicture').click(function(e) {
                e.preventDefault();

                var NopItemId = $("#@Html.FieldIdFor(model => model.PictureId)").val();
                var SliderId = $("#@Html.FieldIdFor(model => model.SliderId)").val();
                var Caption = $("#@Html.FieldIdFor(model => model.Caption)").val();
                var Url = $("#@Html.FieldIdFor(model => model.Url)").val();
                var FilePath = $("#@Html.FieldIdFor(model => model.FilePath)").val();
                var DisplayOrder = $("#@Html.FieldIdFor(model => model.DisplayOrder)").val();

                $('#addProductPicture').attr('disabled', true);
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("CreateItem", "Slider"))",
                    data: {
                        "PictureId": NopItemId,
                        "Caption": Caption,
                        "SliderId": SliderId,
                        "Url": Url,
                        "DisplayOrder": DisplayOrder,
                        "FilePath": FilePath
                    },
                    success: function(data) {
                        var productpicturesGrid = $("#productpictures-grid");
                        productpicturesGrid.data('kendoGrid').dataSource.read();
                        $('#addProductPicture').attr('disabled', false);
                    },
                    error: function(xhr, ajaxOptions, thrownError) {
                        alert('Failed to add product picture.');
                        $('#addProductPicture').attr('disabled', false);
                    }
                });
                return false;
            });
        });
</script>

<div id="productpictures-grid"></div>

<div style="padding: 25px 0">
    <form>
        <fieldset>
            <legend><strong>Add Items</strong></legend>
            <table class="adminContent">
                <tr>
                    <td class="adminTitle">@Html.NopLabelFor(model => model.PictureId):</td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.PictureId)
                        @Html.ValidationMessageFor(model => model.PictureId)
                    </td>
                </tr>
                <tr>
                    <td class="adminData">@Html.HiddenFor(model => model.SliderId)</td>
                </tr>

                <tr>
                    <td class="adminData">@Html.HiddenFor(model => model.Id)</td>
                </tr>
                <tr>
                    <td class="adminTitle">@Html.NopLabelFor(model => model.Caption):</td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.Caption)
                        @Html.ValidationMessageFor(model => model.Caption)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">@Html.NopLabelFor(model => model.Url):</td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.Url)
                        @Html.ValidationMessageFor(model => model.Url)
                    </td>
                </tr>
                <tr>
                    <td class="adminTitle">@Html.NopLabelFor(model => model.DisplayOrder):</td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.DisplayOrder)
                        @Html.ValidationMessageFor(model => model.DisplayOrder)
                    </td>
                </tr>
            </table>
        </fieldset>
        <br />
        <table class="adminContent">
            <tr>
                <td colspan="2">
                    <input type="submit" id="addProductPicture" name="save" class="K-button" value="Save" />
                </td>
            </tr>
        </table>
    </form>

</div>
<script>
        $(document).ready(function() {
            $("#productpictures-grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("GetItemsList", "Slider", new { SliderId = Model.Slider.Id}))",
                            type: "POST",
                            dataType: "json"
                        },
                        update: {
                            url: "@Html.Raw(Url.Action("UpdateItem", "Slider"))",
                            type: "POST",
                            dataType: "json"
                        },
                        destroy: {
                            url: "@Html.Raw(Url.Action("DeleteItem", "Slider"))",
                            type: "POST",
                            dataType: "json"
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                        model: {
                            id: "SliderId",
                            fields: {
                                DisplayOrder: { editable: true, type: "string" },
                                FilePath: { editable: false, type: "string" },
                                Caption: { editable: true, type: "string" },
                                Url: { editable: true, type: "string" },
                                NopItemId: { editable: false, visible: false, type: "number" },
                                SliderId: { editable: false, visible: false, type: "number" }
                            }
                        }
                    },
                    requestEnd: function(e) {
                        if (e.type == "update") {
                            this.read();
                        }
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                editable: {
                    confirmation: true,
                    mode: "inline"
                },
                scrollable: false,
                columns: [
                    {
                        field: "FilePath",
                        title: "Item",
                        template: '<img alt="#=SliderId#" src="#=FilePath#" width="150" />',
                        width: 200
                    }, {
                        field: "Caption",
                        title: "Caption",
                        //integer format
                        width: 150
                    },
                    {
                        field: "Url",
                        title: "Url",
                        //integer format
                        width: 150
                    },
                    {
                        field: "DisplayOrder",
                        title: "DisplayOrder",
                        //integer format
                        width: 150
                    }, {
                        command: [
                            {
                                name: "edit",
                                text: "Edit"
                            }, {
                                name: "destroy",
                                text: "Delete"
                            }
                        ],
                        width: 200
                    }
                ]
            });
        });
</script>

Nop.Plugin.Widget.NopSlider/Views/ManageSliders.cshtml
@using Nop.Web.Framework;
@using Nop.Plugin.Widgets.NopSlider.Domain.Enum;

@{
    Layout = "_AdminLayout.cshtml";
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-catalog.png")" alt="" />
        Manage Sliders
    </div>
    <div class="options">
        <a href="@Url.Action("/CreateBanner")" class="k-button">New Banner</a>
        <a href="@Url.Action("/CreateCategoryBanner")" class="k-button">New Category Banner</a>
        <a href="@Url.Action("/CreateCarousel")" class="k-button">New Carousel</a>
        <a href="@Url.Action("/CreateDirectCarousel")" class="k-button">New Direct Carousel</a>

    </div>
</div>
<div id="sliders"></div>

<script>
    $(document).ready(function () {
        $("#sliders").kendoGrid({
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("ListSliders", "Slider"))",
                        type: "POST",
                        dataType: "json"
                    },
                    update: {
                        url: "@Html.Raw(Url.Action("UpdateSlider", "Slider"))",
                        type: "POST",
                        dataType: "json"
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("DeleteSlider", "Slider"))",
                        type: "POST",
                        dataType: "json"
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            Id: { editable: true, type: "number" },
                            SliderName: { editable: false, type: "string" },
                            IsActive: { editable: true, type: "boolean" },
                            SliderTypeName: { editable: false, type: "string" },
                            IconChevronActive: { editable: true, type: "boolean" },
                            DisplayOrder: { editable: true, type: "number" }
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "update") {
                        this.read();
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: true,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "SliderName",
                title: "Nop Slider Name",
                template: '#if(SliderType == 0) {#<a href="/Slider/UpdateBanner?SliderId=#=Id#">#=SliderName#</a> #} else if(SliderType == 1) {#<a href="/Slider/UpdateCategoryBanner?SliderId=#=Id#">#=SliderName#</a> #} else if(SliderType == 2) {#<a href="/Slider/UpdateCarousel?SliderId=#=Id#">#=SliderName#</a> #} else{#<a href="/Slider/UpdateDirectCarousel?SliderId=#=Id#">#=SliderName#</a> #}#',
                width: 150
            }, {
                field: "IsActive",
                title: "Is Active",
                //integer format
                width: 150
            },
             {
                 field: "SliderTypeName",
                 title: "Slider Type",
                 //integer format
                 width: 150
             },
            {
                field: "IconChevronActive",
                title: "Icon Chevron Active",
                //integer format
                width: 150
            },
               {
                   field: "DisplayOrder",
                   title: "Display Order",
                   //integer format
                   width: 150
               },
            {
                command: [{
                    name: "edit",
                    text: "@T("Admin.Common.Edit")"
                }, {
                    name: "destroy",
                    text: "@T("Admin.Common.Delete")"
                }],
                width: 200
            }]
        });
    });
</script>

Nop.Plugin.Widget.NopSlider/Views/SliderWidget.cshtml
@using Nop.Core.Data
@using Nop.Data
@using Nop.Plugin.Widget.NopSlider.Domain
@using Nop.Web.Framework;
@using Nop.Web.Framework.UI;
@using Nop.Plugin.Widgets.NopSlider.Domain.Enum
@model IEnumerable<Nop.Plugin.Widgets.NopSlider.Model.BannerModel>

@{
    Layout = null;
    Html.AddCssFileParts(ResourceLocation.Head, "~/Plugins/Widgets.NopSlider/Content/owl.carousel.css");
    Html.AddCssFileParts(ResourceLocation.Head, "~/Plugins/Widgets.NopSlider/Content/owl.theme.css");
    Html.AddCssFileParts(ResourceLocation.Head, "~/Plugins/Widgets.NopSlider/Content/owl.transitions.css");
    Html.AddCssFileParts(ResourceLocation.Head, "~/Plugins/Widgets.NopSlider/Content/Stylesheet1.css");
    Html.AddScriptParts(ResourceLocation.Head, "~/Plugins/Widgets.NopSlider/Scripts/owl.carousel.js");

    ViewBag.id = ViewBag.id;
}
@foreach (var item in Model)
{
    <div class="hidden">
        <div class="SliderId">@item.Id</div>
    </div>      

    if (item.SliderType == SliderType.Banner)
    {
        if (item.NavigationButtonPosition == "banner_top")
        {
            <div class="customNavigation row">
                <a class="btn prev-@item.Id">Previous</a>
                <a class="btn next-@item.Id">Next</a>
                <a class="btn play-@item.Id">Autoplay</a>
                <a class="btn stop-@item.Id">Stop</a>
            </div>
        }
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <div id="owl-demo-@item.Id" class="owl-carousel owl-theme">

                @foreach (var image in item.Items)
                {
                    if (image.ProductId == 0)
                    {
                        <div>
                            <a href="@image.Url" target="_blank"><img src="@image.FilePath" alt="@image.Caption" width="100%"></a>
                        </div>

                    }
                }

            </div>
        </div>
        if (item.NavigationButtonPosition == "banner_bottom")
        {
            <div class="customNavigation">
                <a class="btn prev-@item.Id">Previous</a>
                <a class="btn next-@item.Id">Next</a>
                <a class="btn play-@item.Id">Autoplay</a>
                <a class="btn stop-@item.Id">Stop</a>
            </div>
        }
        <div class="hidden">
            <div class="IsProgressBar-@item.Id">@item.IsProgressBar</div>
            <div class="ProgressBarPosition-@item.Id">@item.ProgressBarPostition</div>
            <div class="TransitionStyle-@item.Id">@item.TransitionStyle</div>
            <div class="Interval-@item.Id">@item.Interval</div>
            @if (item.IconChevronActive == true)
            {
                <div class="IconChevronActive-@item.Id">true</div>
            }
            else
            {

                <div class="IconChevronActive-@item.Id">false</div>
            }
            @if (@item.IsMouseDragOn == true)
            {
                <div class="IsMouseDragOn-@item.Id">true</div>
            }
            else
            {
                <div class="IsMouseDragOn-@item.Id">false</div>
            }

        </div>
    <script>
        $(document).ready(function () {
            var time = parseInt($(".Interval-@item.Id").text(), 10); // time in seconds
            var $progressBar,
                $bar,
                $elem,
                isPause = false,
                tick,
                percentTime;
            chevronActive = $(".IconChevronActive-@item.Id").text();
            chevronActive_bool = chevronActive == "true" ? true : false;
            mouseDragOn = $(".IsMouseDragOn-@item.Id").text();
            mouseDragOn_bool = mouseDragOn == "true" ? true : false;

            var owl = $("#owl-demo-@item.Id");
            owl.owlCarousel({

                itemsDesktop: [1000, 2], //5 items between 1000px and 901px
                itemsDesktopSmall: [900, 1], // betweem 900px and 601px
                itemsTablet: [600, 1], //2 items between 600 and 0
                itemsMobile: false,  // itemsMobile disabled - inherit from itemsTablet option
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true,
                afterInit: progressBar,
                afterMove: moved,
                startDragging: pauseOnDragging,
                mouseDrag: mouseDragOn_bool,
                transitionStyle: $(".TransitionStyle-@item.Id").show().html(),
                navigation: chevronActive_bool,
                navigationText: [
                  "<i class='icon-chevron-left icon-white'><</i>",
                  "<i class='icon-chevron-right icon-white'>></i>"
                ]
            });

            owl.trigger('owl.play', 7000);

            // Custom Navigation Events
            $(".next-@item.Id").click(function () {
                owl.trigger('owl.next');
            });
            $(".prev-@item.Id").click(function () {
                owl.trigger('owl.prev');
            });
            $(".play-@item.Id").click(function () {
                owl.trigger('owl.play', 7000); //owl.play event accept autoPlay speed as second parameter
                isPause = false;
            });
            $(".stop-@item.Id").click(function () {
                owl.trigger('owl.stop');
                isPause = true;
            });
            //$(".item").first().addClass("active");
            //$('.carousel-indicators li').first().addClass("active");

            // Init progressBar where elem is $("#owl-demo")
            function progressBar(elem) {
                $elem = elem;
                if ($(".IsProgressBar-@item.Id").show().html() == "True") {
                    //build progress bar elements
                    buildProgressBar();
                    //start counting
                    start();
                }
            }

            //create div#progressBar and div#bar then prepend to $("#owl-demo")
            function buildProgressBar() {
                if ($(".ProgressBarPosition-@item.Id").show().html() == "banner_top") {
                    progressBarOnTop();
                }
                if ($(".ProgressBarPosition-@item.Id").show().html() == "banner_bottom") {
                    progressBarOnBottom();
                }

            }
            function progressBarOnTop() {
                $progressBar = $("<div>", {
                    id: "progressBar"
                });
                $bar = $("<div>", {
                    id: "bar"
                });
                $progressBar.append($bar).prependTo($elem);
            }
            function progressBarOnBottom() {
                $progressBar = $("<div>", {
                    id: "progressBar"
                });
                $bar = $("<div>", {
                    id: "bar"
                });
                $progressBar.append($bar).appendTo($elem);
            }

            function start() {
                //reset timer
                percentTime = 0;
                //run interval every 0.01 second
                tick = setInterval(interval, 10);
            };

            function interval() {
                if (isPause === false) {
                    percentTime += 1 / time;
                    if ($(".IsProgressBar-@item.Id").show().html() == "True") {
                        $bar.css({
                            width: percentTime + "%"
                        });
                    }

                    //if percentTime is equal or greater than 100
                    if (percentTime >= 100) {
                        //slide to next item
                        $elem.trigger('owl.next');
                    }
                }
            }

            //pause while dragging
            function pauseOnDragging() {
                isPause = true;
            }

            //moved callback
            function moved() {
                //clear interval
                clearTimeout(tick);
                //start again
                start();
            }

        });
    </script>

    }


    else if(item.SliderType == SliderType.Carousel)
    {
        Html.RenderAction("CarouselWidget", "Slider", new { SliderId = @item.Id });
    }

    else
    {
        Html.RenderAction("DirectCarouselWidget", "Slider");
    }

}